### ISSUE TITLE
homeassistant/raspberrypi4-homeassistant is not up to date

### ISSUE THREAD

**Issue by tijsverkoyen** [home-assistant/docker-base#232]
Sorry to barge in, but I could not find a better place to log this issue. If there is a better place: let me know.

The latest stable release on https://hub.docker.com/r/homeassistant/raspberrypi4-homeassistant is 2023.6.3. While the latest release of Home Assistant is 2023.8. 

I would think some automated process to build the images is stuck? 

Or is the homeassistant/raspberrypi4-homeassistant not supported anymore? And if so: what would be a good replacement?

**Comment by tijsverkoyen** [comment]
Nevermind, I had not read the breaking changes in https://www.home-assistant.io/blog/2023/07/05/release-20237/#breaking-changes.

For future reference:

I have replaced:

```yaml
  homeAssistant:
    container_name: homeAssistant
    image: homeassistant/raspberrypi4-homeassistant:stable
```

with 
```yaml
  homeAssistant:
    container_name: homeAssistant
    image: ghcr.io/home-assistant/home-assistant:stable
```

in my `docker-compose.yaml` file
